services:
  - type: web
    name: producthunt-fetch
    env: python
    plan: free
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    envVars:
      - key: PRODUCTHUNT_TOKEN
        sync: false